import Head from 'next/head'
import HeaderContent from '../components/header-content.component'
import TabContent from '../components/tabs.component'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Free Stock Photos - Pexels</title>
        <meta name="Pexels" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderContent/>
      <TabContent/>

     
  
     
    </div>
  )
}
